### ISSUE TITLE
Difference between motif-scaffolding inference

### ISSUE THREAD

**Issue by OrangeCat7777777** [microsoft/flow-matching#27]
As written in README.md, seems to be two types of motif-scaffolding inference:
```
# Single GPU
python -W ignore experiments/inference_se3_flows.py -cn inference_scaffolding

# Multi GPU
python -W ignore experiments/inference_se3_flows.py -cn inference_scaffolding inference.num_gpus=2

# FrameFlow-guidance
python -W ignore experiments/inference_se3_flows.py -cn inference_scaffolding_guidance
```
What's the difference between the first 2 and the 3rd one? It seems that the 3rd one is the way introduced in the FrameFlow paper?

**Comment by jasonkyuyim** [comment]
The first two use FrameFlow-amortization which is the fine-tuned motif-scaffolding model. The third is FrameFlow-guidance which uses the pre-trained model with reconstruction guidance. They both do motif-scaffolding but in different ways. See the paper for more details on both.

**Comment by OrangeCat7777777** [comment]
Got it. Thanks!
